// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wall.Models;

namespace Wall.Migrations
{
    [DbContext(typeof(wallContext))]
    [Migration("20181210200739_wallMigration")]
    partial class wallMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Wall.Models.Comment", b =>
                {
                    b.Property<int>("cId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<int>("mId");

                    b.Property<string>("text")
                        .IsRequired();

                    b.Property<int>("uId");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("cId");

                    b.HasIndex("mId");

                    b.HasIndex("uId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Wall.Models.Message", b =>
                {
                    b.Property<int>("mId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<string>("text")
                        .IsRequired();

                    b.Property<int>("uId");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("mId");

                    b.HasIndex("uId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Wall.Models.User", b =>
                {
                    b.Property<int>("uId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("first_name")
                        .IsRequired();

                    b.Property<string>("last_name")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<DateTime>("updated_at");

                    b.HasKey("uId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Wall.Models.Comment", b =>
                {
                    b.HasOne("Wall.Models.Message", "Message")
                        .WithMany("comments")
                        .HasForeignKey("mId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Wall.Models.User", "user")
                        .WithMany("comments")
                        .HasForeignKey("uId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Wall.Models.Message", b =>
                {
                    b.HasOne("Wall.Models.User", "user")
                        .WithMany("messages")
                        .HasForeignKey("uId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
